---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: 92-br-vlans
  namespace: <APP_NS>
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "localnet-vlan92",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "netAttachDefName": "<APP_NS/92-br-vlans",
      "vlanID": 92
    }