apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  annotations:
    k8s.v1.cni.cncf.io/policy-for: 2001-dmz-br-vlans
  name: allow-vms-secondary-network
  namespace: 2001-dmz
spec:
  podSelector:
    matchExpressions:
        - key: vm.kubevirt.io/name
          operator: Exists
  ingress:
    - from:
      - ipBlock:
          cidr: 10.0.201.0/24
  policyTypes:
    - Ingress