---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-vlans
spec:
  desiredState:
    interfaces:
      - name: br-vlans
        type: ovs-bridge
        state: up
        bridge:
          allow-extra-patch-ports: true
          options:
            stp: false
          port:
            - name: <PORT NOT USED BY MACHINE-NETWORK i.e. different VLAN or separate NIC>
              vlan:
                mode: trunk
                trunk-tags:
                - id: 92
