---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: 2001-dmz-br-vlans
  namespace: 2001-dmz
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "vlan2001",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "netAttachDefName": "2001-dmz/2001-dmz-br-vlans",
      "vlanID": 2001
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: 2001-dmz-pod-dhcp
  namespace: 2001-dmz
spec:
  config: |-
   {
     "cniVersion": "0.3.1",
     "type": "macvlan",
     "master": "br-vlans.2001",
     "ipam": {
       "type": "dhcp"
     }
   }
