---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: 2002-oss-br-vlans
  namespace: 2002-oss
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "vlan2002",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "netAttachDefName": "2002-oss/2002-oss-br-vlans",
      "vlanID": 2002
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: 2002-oss-pod-dhcp
  namespace: 2002-oss
spec:
  config: |-
   {
     "cniVersion": "0.3.1",
     "type": "macvlan",
     "master": "br-vlans.2002",
     "ipam": {
       "type": "dhcp"
     }
   }
