---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: oss-apps-ingress
  namespace: openshift-ingress-operator
spec:
  domain: oss-apps.sno-3-25.lab.apac-telco.net
  endpointPublishingStrategy:
    type: Private
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/worker: ""
  routeSelector:
    matchExpressions:
      - key: zone
        operator: In
        values:
          - oss
---
apiVersion: v1
kind: Service
metadata:
  name: oss-apps-ingress
  namespace: openshift-ingress
  annotations:
    metallb.universe.tf/address-pool: pool-2003
spec:
  selector:
    ingresscontroller.operator.openshift.io/deployment-ingresscontroller: oss-apps-ingress
  ports:
    - port: 80
      name: 80-tcp
      protocol: TCP
      targetPort: http
    - port: 443
      name: 443-tcp
      protocol: TCP
      targetPort: http
  type: LoadBalancer
---
apiVersion: k8s.ovn.org/v1
kind: EgressService
metadata:
  name: oss-apps-ingress
  namespace: openshift-ingress
spec:
  sourceIPBy: "LoadBalancerIP"
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: sno-3-25
  network: "2003"
