---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: localnet-vlan2003
spec:
  desiredState:
    ovn:
      bridge-mappings:
        - bridge: br-vlans
          localnet: vlan2003
          state: present
