---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: localnet-vlan92
spec:
  desiredState:
    ovn:
      bridge-mappings:
        - bridge: br-vlans
          localnet: vlan92
          state: present
